name: Auto Pull Request

on:
  push:
    branches:
      - main  # Or your default branch

jobs:
  create_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Required to get all history

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Or your preferred version

      - name: Install Dependencies
        run: npm install @octokit/rest

      - name: Create Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Important: Use a secret
        run: |
          COMMIT_SHA=$(git rev-parse HEAD)
          COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          BRANCH_NAME="auto-pr/$COMMIT_SHA"

          # Create a new branch for the PR
          git checkout -b "$BRANCH_NAME"

          # Push the new branch to the remote repository
          git push origin "$BRANCH_NAME"

          # Use Octokit to create the pull request
          node <<EOF
          const { Octokit } = require("@octokit/rest");
          const octokit = new Octokit({ auth: '${{ secrets.GITHUB_TOKEN }}' });

          async function createPullRequest() {
            try {
              const owner = process.env.GITHUB_REPOSITORY_OWNER;
              const repo = process.env.GITHUB_REPOSITORY.split('/')[1]; // Extract repo name

              const response = await octokit.pulls.create({
                owner: owner,
                repo: repo,
                title: '$COMMIT_MESSAGE',
                head: '$BRANCH_NAME',
                base: 'main',
                body: `Automated PR for commit ${COMMIT_SHA}.  Commit message: ${COMMIT_MESSAGE}`,
              });

              console.log('Pull request created:', response.data.html_url);
            } catch (error) {
              console.error('Error creating pull request:', error);
            }
          }

          createPullRequest();
          EOF